name: Actions

on:
  pull_request:
    paths:
      - .devcontainer/devcontainer.json
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Run actionlint
        run: just action-lint

  devcontainer-versions:
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - run: just action-dev-check
