
name: Helm

on:
  pull_request:
    paths:
      - .github/workflows/helm.yml
      - bin/helm*
      - '**/charts/**'

permissions:
  contents: read

jobs:
  helm-docs-diff:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - run: bin/helm-docs-diff
