name: Shell

on:
  pull_request:
    paths:
      - .github/workflows/shell.yml
      - '**/*.sh'

permissions:
  contents: read

jobs:
  # For more information on shellcheck failures:
  # https://github.com/koalaman/shellcheck/wiki/Checks
  shellcheck:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - run: just sh-lint

