name: Shell

on:
  pull_request:
    paths:
      - .github/workflows/shell.yml
      - '**/*.sh'

permissions:
  contents: read

jobs:
  # For more information on shellcheck failures:
  # https://github.com/koalaman/shellcheck/wiki/Checks
  shellcheck:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container: ghcr.io/linkerd/dev:v32-tools
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - run: just sh-lint

